apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ra49y5rvz-dotnet-basic
  janus-idp.io/tekton: ra49y5rvz-dotnet-basic
  backstage.io/kubernetes-id: ra49y5rvz-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ra49y5rvz-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
